name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@5456577541f2da5c938244e2c911d0222927abf7
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        REACT_APP_SOCKET_URL: "https://mud-api.seanson.website"
        BUILD_SCRIPT: npm install && npm run-script build # The build script the action should run prior to deploying.
        CNAME: mud.seanson.website
